return {
	config=
	{
		[1]=
		{
			id = 1,
			item_id = 1,
			item_key = "cash",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_xj",
			name = "奖金",
			desc = "微信红包奖金",
		},
		[2]=
		{
			id = 2,
			item_id = 2,
			item_key = "jipaiqi",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_jipaiqi",
			is_show_bag = 1,
			order = 2,
			name = "记牌器",
			desc = "记牌器",
		},
		[3]=
		{
			id = 3,
			item_id = 3,
			item_key = "diamond",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_icon_diamond",
			name = "钻石",
			desc = "钻石",
		},
		[4]=
		{
			id = 4,
			item_id = 4,
			item_key = "jing_bi",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_jingbi",
			name = "鲸币",
			desc = "鲸币",
		},
		[5]=
		{
			id = 5,
			item_id = 5,
			item_key = "vip",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_btn_close",
			name = "VIP",
			desc = "vip",
		},
		[6]=
		{
			id = 6,
			item_id = 6,
			item_key = "shop_gold_sum",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_money",
			name = "红包券",
			desc = "红包券",
		},
		[7]=
		{
			id = 7,
			item_id = 7,
			item_key = "shop_gold_sum_limit",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_moneyed",
			name = "红包券额度",
			desc = "每日红包券额度",
		},
		[8]=
		{
			id = 8,
			item_id = 8,
			item_key = "room_card",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_rc",
			is_show_bag = 1,
			order = 21,
			name = "房卡",
			desc = "创建房卡游戏时使用",
			use_parm = {"roomcard_hall",},
		},
		[9]=
		{
			id = 9,
			item_id = 9,
			item_key = "frame1",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz1",
			name = "Lv.10",
			desc = "等级头像框",
		},
		[10]=
		{
			id = 10,
			item_id = 10,
			item_key = "frame2",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz2",
			name = "Lv.20",
			desc = "等级头像框",
		},
		[11]=
		{
			id = 11,
			item_id = 11,
			item_key = "frame3",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz3",
			name = "Lv.30",
			desc = "等级头像框",
		},
		[12]=
		{
			id = 12,
			item_id = 12,
			item_key = "frame4",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz4",
			name = "Lv.40",
			desc = "等级头像框",
		},
		[13]=
		{
			id = 13,
			item_id = 13,
			item_key = "frame5",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz5",
			name = "Lv.50",
			desc = "等级头像框",
		},
		[14]=
		{
			id = 14,
			item_id = 14,
			item_key = "frame6",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz6",
			name = "Lv.60",
			desc = "等级头像框",
		},
		[15]=
		{
			id = 15,
			item_id = 15,
			item_key = "frame7",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz7",
			name = "Lv.70",
			desc = "等级头像框",
		},
		[16]=
		{
			id = 16,
			item_id = 16,
			item_key = "frame8",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz8",
			name = "Lv.80",
			desc = "等级头像框",
		},
		[17]=
		{
			id = 17,
			item_id = 17,
			item_key = "frame9",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz9",
			name = "Lv.90",
			desc = "等级头像框",
		},
		[18]=
		{
			id = 18,
			item_id = 18,
			item_key = "emoticon1",
			lose_time = -1,
			is_local_icon = 1,
			image = "ddz_game_ui_water",
			name = "泼水表情",
			desc = "高级互动表情",
		},
		[19]=
		{
			id = 19,
			item_id = 19,
			item_key = "emoticon2",
			lose_time = -1,
			is_local_icon = 1,
			image = "ddz_game_ui_guo",
			name = "平底锅表情",
			desc = "高级互动表情",
		},
		[20]=
		{
			id = 20,
			item_id = 20,
			item_key = "emoticon3",
			lose_time = -1,
			is_local_icon = 1,
			image = "ddz_game_ui_th",
			name = "戴墨镜表情",
			desc = "高级互动表情",
		},
		[21]=
		{
			id = 21,
			item_id = 21,
			item_key = "emoticon4",
			lose_time = -1,
			is_local_icon = 1,
			image = "ddz_game_ui_pig",
			name = "变猪表情",
			desc = "高级互动表情",
		},
		[22]=
		{
			id = 22,
			item_id = 22,
			item_key = "chat",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhk",
			name = "方言特色短语",
			desc = "高级快捷短语",
		},
		[23]=
		{
			id = 23,
			item_id = 23,
			item_key = "broadcast",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_gb",
			name = "登录全服广播",
			desc = "登录时全服播放欢迎广播",
		},
		[24]=
		{
			id = 24,
			item_id = 24,
			item_key = "jipaiqi_free",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_jipaiqi",
			name = "免费记牌器",
			desc = "免费使用记牌器",
		},
		[25]=
		{
			id = 25,
			item_id = 101,
			item_key = "match_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "bag_icon_hxs",
			is_show_bag = 0,
			order = -1,
			name = "比赛券",
			desc = "用于参加比赛场的比赛",
		},
		[26]=
		{
			id = 26,
			item_id = 25,
			item_key = "frame10",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz10",
			name = "Lv.100",
			desc = "等级头像框",
		},
		[27]=
		{
			id = 27,
			item_id = 26,
			item_key = "prop_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_csj",
			is_show_bag = 0,
			order = 0,
			name = "比赛场门票",
			desc = "可用于参加所有锦标赛",
			use_parm = {"match_hall","hbs",},
		},
		[28]=
		{
			id = 28,
			item_id = 27,
			item_key = "prop_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_qys",
			is_show_bag = 1,
			order = 4,
			name = "千元赛门票",
			desc = "用于报名千元大奖赛",
			use_parm = {"match_hall","gms",},
		},
		[29]=
		{
			id = 29,
			item_id = 28,
			item_key = "real_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_csj",
			is_show_bag = 0,
			order = 0,
			name = "黑锅",
			desc = "黑锅",
			real_object = 1,
		},
		[30]=
		{
			id = 30,
			item_id = 29,
			item_key = "prop_hammer_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cz1",
			is_show_bag = 1,
			order = 17,
			name = "玩具锤",
			desc = "内部充气的玩具锤，小朋友们的最爱",
			use_parm = {"hall_egg","prop_hammer_1"},
		},
		[31]=
		{
			id = 31,
			item_id = 30,
			item_key = "prop_hammer_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cz2",
			is_show_bag = 1,
			order = 18,
			name = "木锤",
			desc = "看起来似乎不太经用的木头锤子",
			use_parm = {"hall_egg","prop_hammer_2"},
		},
		[32]=
		{
			id = 32,
			item_id = 31,
			item_key = "prop_hammer_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cz3",
			is_show_bag = 1,
			order = 19,
			name = "银锤",
			desc = "虽然看起来挺像，不过这可不是那把能放电的锤子",
			use_parm = {"hall_egg","prop_hammer_3"},
		},
		[33]=
		{
			id = 33,
			item_id = 32,
			item_key = "prop_hammer_4",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cz4",
			is_show_bag = 1,
			order = 20,
			name = "金锤",
			desc = "听说下雨天金锤和金蛋更配哦！",
			use_parm = {"hall_egg","prop_hammer_4"},
		},
		[34]=
		{
			id = 34,
			item_id = 33,
			item_key = "expression_54",
			lose_time = -1,
			is_local_icon = 1,
			image = "ddz_game_ui_666",
			name = "666表情",
			desc = "666表情",
		},
		[35]=
		{
			id = 35,
			item_id = 34,
			item_key = "prop_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_wys",
			is_show_bag = 1,
			order = 3,
			name = "万元赛门票",
			desc = "用于报名万元大奖赛",
			use_parm = {"match_hall","gms",},
		},
		[36]=
		{
			id = 36,
			item_id = 35,
			item_key = "prop_4",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_jyhd",
			is_show_bag = 1,
			order = 5,
			name = "企业赛门票",
			desc = "用于报名企业赛",
			use_parm = {"match_hall","gms",},
		},
		[37]=
		{
			id = 37,
			item_id = 36,
			item_key = "prop_5",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_yys",
			is_show_bag = 1,
			order = 10,
			name = "一元赛门票",
			desc = "用于报名一元赛",
			use_parm = {"match_hall","hbs",},
		},
		[38]=
		{
			id = 38,
			item_id = 37,
			item_key = "fake1",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_moneyywy",
			is_show_bag = 0,
			name = "千元第一",
			desc = "第一",
		},
		[39]=
		{
			id = 39,
			item_id = 38,
			item_key = "fake2",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_money300",
			is_show_bag = 0,
			name = "千元第二",
			desc = "第二",
		},
		[40]=
		{
			id = 40,
			item_id = 39,
			item_key = "fake3",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_money10000",
			is_show_bag = 0,
			name = "千元第三",
			desc = "第三",
		},
		[41]=
		{
			id = 41,
			item_id = 40,
			item_key = "obj_qianyuansai_ticket",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_qys",
			is_show_bag = 1,
			order = 1,
			name = "千元赛门票",
			desc = "千元赛限时门票，限7天内使用！",
			desc_extra = "<size=40><color=#FF0000FF>限时</color><color=#FFF06E>门票，有效时间</color><color=#FF0000FF>7天</color></size>",
			use_parm = {"match_hall","gms",},
		},
		[42]=
		{
			id = 42,
			item_id = 41,
			item_key = "prop_5y",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_5ys",
			is_show_bag = 1,
			order = 9,
			name = "五元赛门票",
			desc = "用于报名五元红包赛",
			use_parm = {"match_hall","hbs",},
		},
		[43]=
		{
			id = 43,
			item_id = 42,
			item_key = "prop_20y",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_20ys",
			is_show_bag = 1,
			order = 8,
			name = "二十元赛门票",
			desc = "用于报名二十元红包赛",
			use_parm = {"match_hall","hbs",},
		},
		[44]=
		{
			id = 44,
			item_id = 43,
			item_key = "prop_100y",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_100ys",
			is_show_bag = 1,
			order = 6,
			name = "百元赛门票",
			desc = "用于报名一百元红包赛",
			use_parm = {"match_hall","hbs",},
		},
		[45]=
		{
			id = 45,
			item_id = 44,
			item_key = "prop_50y",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_50ys",
			is_show_bag = 1,
			order = 7,
			name = "五十元赛门票",
			desc = "用于报名五十元红包赛",
			use_parm = {"match_hall","hbs",},
		},
		[46]=
		{
			id = 46,
			item_id = 45,
			item_key = "fish_coin",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_icon_yb",
			is_show_bag = 1,
			order = 1,
			name = "捕鱼币",
			desc = "用于捕鱼消耗",
		},
		[47]=
		{
			id = 47,
			item_id = 46,
			item_key = "prop_fish_frozen",
			lose_time = -1,
			is_local_icon = 1,
			image = "by_btn_bd",
			is_show_bag = 1,
			order = 16,
			name = "冰冻",
			desc = "冰冻全场鱼",
			use_parm = {"game_FishingHall",},
			tag = 2,
		},
		[48]=
		{
			id = 48,
			item_id = 47,
			item_key = "prop_fish_lock",
			lose_time = -1,
			is_local_icon = 1,
			image = "by_btn_sd",
			is_show_bag = 1,
			order = 15,
			name = "锁定",
			desc = "锁定攻击鱼",
			use_parm = {"game_FishingHall",},
			tag = 2,
		},
		[49]=
		{
			id = 49,
			item_id = 48,
			item_key = "expression_57",
			lose_time = -1,
			is_local_icon = 1,
			image = "pay_icon_pig",
			name = "猪头表情",
			desc = "猪头表情",
		},
		[50]=
		{
			id = 50,
			item_id = 49,
			item_key = "prop_50hf",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_50ys",
			is_show_bag = 1,
			order = 11,
			name = "五十话费赛门票",
			desc = "用于报名50元免费话费赛",
			use_parm = {"match_hall","sws",},
		},
		[51]=
		{
			id = 51,
			item_id = 50,
			item_key = "prop_100hf",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_100ys",
			is_show_bag = 1,
			order = 10,
			name = "一百话费赛门票",
			desc = "用于报名100元免费话费赛",
			use_parm = {"match_hall","sws",},
		},
		[52]=
		{
			id = 52,
			item_id = 51,
			item_key = "prop_zongzi",
			lose_time = -1,
			is_local_icon = 1,
			image = "ddz_game_ui_666",
			is_show_bag = 0,
			order = 1,
			name = "粽子",
			desc = "捕鱼收集粽子赢大奖",
		},
		[53]=
		{
			id = 53,
			item_id = 52,
			item_key = "obj_fish_free_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "bygame_icon_danmf2",
			is_show_bag = 1,
			order = 12,
			name = "免费时刻",
			desc = "触发免费时刻",
			use_parm = {"game_FishingHall",},
			tag = 2,
		},
		[54]=
		{
			id = 54,
			item_id = 53,
			item_key = "obj_fish_crit_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "bygame_icon_sbsk",
			is_show_bag = 1,
			order = 14,
			name = "双倍时刻",
			desc = "触发双倍时刻",
			use_parm = {"game_FishingHall",},
			tag = 2,
		},
		[55]=
		{
			id = 55,
			item_id = 54,
			item_key = "obj_fish_power_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "bygame_icon_cjhl",
			is_show_bag = 1,
			order = 13,
			name = "超级火力",
			desc = "触发超级火力",
			use_parm = {"game_FishingHall",},
			tag = 2,
		},
	},
}