return {
	config=
	{
		[1]=
		{
			id = 1,
			ID = 1,
			noCloseUI = 0,
			order = 5,
			type = "activity",
			title = "打比赛赢红包！",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_1",
			is_local_icon = 1,
			gotoUI = {"match_hall",},
			beginTime = -1,
			endTime = 1554912000,
		},
		[2]=
		{
			id = 2,
			ID = 2,
			noCloseUI = 0,
			order = 3,
			type = "activity",
			title = "双11礼物独宠一人！",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_7",
			is_local_icon = 1,
			tag = "new",
			beginTime = -1,
			endTime = -1,
		},
		[3]=
		{
			id = 3,
			ID = 3,
			noCloseUI = 0,
			order = 1,
			type = "notice",
			title = "不删号内测公告",
			isOnOff = 1,
			showType = "notice",
			parmData = "亲爱的玩家朋友们：\n游戏版本升级将于2019年1月16日（周三）上午9点开启第2阶段不删档内测，安卓和IOS版本手机皆可参与游戏，新版本福利high到爆，登录游戏可领。\n福利1：新人红包福利人人可领16元红包券！\n福利2：金猪礼包福利，每天玩游戏领5元微信红包！\n内测期间如遇到任务问题或有更好的建议请加客服微信jyddz02进行反馈。\n\n                                                                    《鲸鱼家园》运营团队\n                                                                                       2019年1月16日",
			tag = "normal",
			beginTime = -1,
			endTime = -1,
		},
		[4]=
		{
			id = 4,
			ID = 4,
			noCloseUI = 0,
			order = 0,
			type = "activity",
			title = "鲸鱼杯大奖赛",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_5",
			is_local_icon = 1,
			gotoUI = {"citymatch_hall",},
			tag = "hot",
			beginTime = -1,
			endTime = -1,
		},
		[5]=
		{
			id = 5,
			ID = 5,
			noCloseUI = 1,
			order = 6,
			type = "activity",
			title = "2元超值礼包",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_4",
			is_local_icon = 1,
			gotoUI = {"2_gift_bag",},
			tag = "hot",
			beginTime = -1,
			endTime = -1,
		},
		[6]=
		{
			id = 6,
			ID = 6,
			noCloseUI = 0,
			order = 4,
			type = "notice",
			title = "官方微信群",
			isOnOff = 1,
			showType = "notice",
			parmData = "亲爱的玩家朋友们：\n\n游戏官方微信群正式上线啦，请添加客服微信号：jyddz02，由客服拉您进群，群里不定时红包雨，还有漂亮的小姐姐小哥哥可以聊天哦，期待您的加入！\n感谢您对本游戏的热爱和支持！\n\n                                                             《鲸鱼家园》运营团队敬上\n                                                                          2018年10月12日",
			tag = "normal",
			beginTime = -1,
			endTime = -1,
		},
		[7]=
		{
			id = 7,
			ID = 7,
			noCloseUI = 0,
			order = 4,
			type = "activity",
			title = "现金奖池来袭！",
			isOnOff = 0,
			showType = "image",
			is_local_icon = 1,
			gotoUI = {"free_hall",},
			tag = "normal",
			beginTime = -1,
			endTime = -1,
		},
		[8]=
		{
			id = 8,
			ID = 8,
			noCloseUI = 0,
			order = 2,
			type = "activity",
			title = "房卡场免费啦！",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_8",
			is_local_icon = 1,
			gotoUI = {"roomcard_hall",},
			tag = "hot",
			beginTime = -1,
			endTime = -1,
		},
		[9]=
		{
			id = 9,
			ID = 9,
			noCloseUI = 0,
			order = 1,
			type = "activity",
			title = "合伙人礼包",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_9",
			is_local_icon = 1,
			gotoUI = {"hall_tgr",},
			tag = "hot",
			beginTime = -1,
			endTime = -1,
		},
		[10]=
		{
			id = 10,
			ID = 10,
			noCloseUI = 0,
			order = 3,
			type = "notice",
			title = "兑奖公告",
			isOnOff = 1,
			showType = "notice",
			parmData = "兑换商城温馨提示：\n\n1.红包劵是平台回馈给玩家的一种免费获得的累积型兑换券，可以在兑换商城中兑换话费或者实物；红包券可以通过完成牌局任务，参加公益锦标赛赢取，不能通过充值、玩家之间的转让获得；\n\n2.利用BUG等不正当手段获取的红包券，一经查实，红包券将清零及禁止兑换处理；\n\n3.为了更好的向玩家提供服务，兑换商城将会对不同的玩家ID推送不同的礼品内容；\n\n4.为了进行合理的风险控制以及客观情况的要求，兑换存在库存、区域、以及每日兑换频率等限制；\n\n5.根据运营以及供货方的货源情况，我们将不定期上架或者下架礼品内容；\n\n6.竟娱互动保留最终解释权。",
			tag = "normal",
			beginTime = -1,
			endTime = -1,
		},
		[11]=
		{
			id = 11,
			ID = 11,
			noCloseUI = 0,
			order = 2,
			type = "notice",
			title = "重要公告",
			isOnOff = 0,
			showType = "notice",
			parmData = "重要公告：\n\n本平台倡导绿色休闲游戏，游戏中的鲸币为道具，不具有任何的实际货币价值，只限于玩家在游戏中使用。同时，本平台对玩家的鲸币不提供任何形式的官方回购、直接或间接兑换现金、兑换实物、相互转赠、转让等服务。\n\n在此，本平台明令禁止玩家之间任何形式的鲸币交易，鲸币转让等行为，坚决抵制低俗、不健康或涉及赌博等违法违规行为，以及其他违背游戏公平的作弊行为，一经核实，将被处以禁止登陆游戏、删除游戏数据等处罚。",
			tag = "normal",
			beginTime = -1,
			endTime = -1,
		},
		[12]=
		{
			id = 12,
			ID = 12,
			noCloseUI = 0,
			order = 1,
			type = "activity",
			title = "双旦礼包",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_10",
			is_local_icon = 1,
			gotoUI = {"hall_sd",},
			tag = "hot",
			beginTime = -1,
			endTime = -1,
		},
		[13]=
		{
			id = 13,
			ID = 13,
			noCloseUI = 1,
			order = 6,
			type = "activity",
			title = "千元赛礼包",
			isOnOff = 1,
			showType = "image",
			parmData = "ad_12",
			is_local_icon = 1,
			shop_id = 13,
			gotoUI = {"hall_gift_13",},
			tag = "hot",
			beginTime = -1,
			endTime = -1,
		},
		[14]=
		{
			id = 14,
			ID = 14,
			noCloseUI = 1,
			order = 6,
			type = "activity",
			title = "金猪礼包",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_13",
			is_local_icon = 1,
			gotoUI = {"hall_golden_pig",},
			tag = "hot",
			beginTime = -1,
			endTime = -1,
		},
		[15]=
		{
			id = 15,
			ID = 15,
			noCloseUI = 1,
			order = 7,
			type = "activity",
			title = "敲敲乐",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_14",
			is_local_icon = 1,
			gotoUI = {"hall_egg",},
			tag = "hot",
			beginTime = -1,
			endTime = -1,
		},
		[16]=
		{
			id = 16,
			ID = 16,
			noCloseUI = 1,
			order = -11,
			type = "activity",
			title = "春节礼包",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_20",
			is_local_icon = 1,
			shop_id = 21,
			gotoUI = {"hall_gift_21",},
			tag = "new",
			beginTime = -1,
			endTime = -1,
		},
		[17]=
		{
			id = 17,
			ID = 17,
			noCloseUI = 1,
			order = -12,
			type = "activity",
			title = "天降财神",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_17",
			is_local_icon = 1,
			gotoUI = {"free_hall",},
			tag = "normal",
			beginTime = -1,
			endTime = -1,
		},
		[18]=
		{
			id = 18,
			ID = 18,
			noCloseUI = 1,
			order = -13,
			type = "activity",
			title = "五子棋来了！",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_23",
			is_local_icon = 1,
			gotoUI = {"free_hall",},
			tag = "new",
			beginTime = -1,
			endTime = -1,
		},
		[19]=
		{
			id = 19,
			ID = 19,
			noCloseUI = 1,
			order = -14,
			type = "activity",
			title = "女神礼包",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_21",
			is_local_icon = 1,
			shop_id = 28,
			gotoUI = {"hall_gift_28",},
			tag = "new",
			beginTime = -1,
			endTime = -1,
		},
		[20]=
		{
			id = 20,
			ID = 20,
			noCloseUI = 1,
			order = -15,
			type = "activity",
			title = "敲爱女神节",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_22",
			is_local_icon = 1,
			gotoUI = {"hall_egg",},
			tag = "hot",
			beginTime = -1,
			endTime = -1,
		},
		[21]=
		{
			id = 21,
			ID = 21,
			noCloseUI = 1,
			order = -16,
			type = "activity",
			title = "回馈礼包",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_24",
			is_local_icon = 1,
			shop_id = 29,
			gotoUI = {"hall_gift_29",},
			tag = "new",
			beginTime = -1,
			endTime = 1554912000,
		},
		[22]=
		{
			id = 22,
			ID = 22,
			noCloseUI = 1,
			order = -17,
			type = "activity",
			title = "敲敲乐",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_25",
			is_local_icon = 1,
			gotoUI = {"hall_egg",},
			tag = "hot",
			beginTime = -1,
			endTime = -1,
		},
		[23]=
		{
			id = 23,
			ID = 23,
			noCloseUI = 1,
			order = -18,
			type = "activity",
			title = "踏春礼包",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_26",
			is_local_icon = 1,
			shop_id = 35,
			gotoUI = {"hall_gift_35",},
			tag = "new",
			beginTime = -1,
			endTime = 1554912000,
		},
		[24]=
		{
			id = 24,
			ID = 24,
			noCloseUI = 1,
			order = -19,
			type = "activity",
			title = "敲敲乐",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_25",
			is_local_icon = 0,
			gotoUI = {"hall_egg",},
			tag = "hot",
			beginTime = -1,
			endTime = 1554912000,
		},
		[25]=
		{
			id = 25,
			ID = 25,
			noCloseUI = 1,
			order = 8,
			type = "activity",
			title = "关注公众号",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_27",
			is_local_icon = 1,
			tag = "normal",
			beginTime = -1,
			endTime = -1,
		},
		[26]=
		{
			id = 26,
			ID = 26,
			noCloseUI = 1,
			order = -21,
			type = "activity",
			title = "打高倍领鲸币",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_28",
			is_local_icon = 1,
			tag = "hot",
			beginTime = 1555030800,
			endTime = -1,
		},
		[27]=
		{
			id = 27,
			ID = 27,
			noCloseUI = 0,
			order = -22,
			type = "activity",
			title = "招募推广员",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_29",
			is_local_icon = 1,
			gotoUI = {"copy_gzh_sw",},
			tag = "hot",
			beginTime = -1,
			endTime = -1,
		},
		[28]=
		{
			id = 28,
			ID = 28,
			noCloseUI = 1,
			order = -23,
			type = "activity",
			title = "捕鱼预约",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_30",
			is_local_icon = 1,
			gotoUI = {"copy_gzh","JYDDZ01",},
			tag = "new",
			beginTime = -1,
			endTime = -1,
		},
		[29]=
		{
			id = 29,
			ID = 29,
			noCloseUI = 1,
			order = 3,
			type = "activity",
			title = "鲸鱼周卡",
			isOnOff = 1,
			showType = "image",
			parmData = "ad_34",
			is_local_icon = 1,
			gotoUI = {"weekly_card",},
			tag = "hot",
			beginTime = -1,
			endTime = -1,
		},
		[30]=
		{
			id = 30,
			ID = 30,
			noCloseUI = 1,
			order = -24,
			type = "activity",
			title = "财神模式",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_35",
			is_local_icon = 1,
			gotoUI = {"hall_egg","mode_cs",},
			tag = "hot",
			beginTime = -1,
			endTime = -1,
		},
		[31]=
		{
			id = 31,
			ID = 31,
			noCloseUI = 1,
			order = -26,
			type = "activity",
			title = "捕鱼累计赢金",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_32",
			is_local_icon = 1,
			gotoUI = {"game_FishingHall","add_glod",},
			tag = "new",
			beginTime = -1,
			endTime = -1,
		},
		[32]=
		{
			id = 32,
			ID = 32,
			noCloseUI = 1,
			order = -24,
			type = "activity",
			title = "夏日回馈",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_31",
			is_local_icon = 1,
			shop_id = 38,
			gotoUI = {"hall_gift_38",},
			tag = "hot",
			beginTime = -1,
			endTime = -1,
		},
		[33]=
		{
			id = 33,
			ID = 33,
			noCloseUI = 1,
			order = -23,
			type = "activity",
			title = "回归奖励",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_36",
			is_local_icon = 1,
			gotoUI = {"copy_gzh","JYDDZ01",},
			tag = "hot",
			beginTime = -1,
			endTime = -1,
		},
		[34]=
		{
			id = 34,
			ID = 34,
			noCloseUI = 1,
			order = -26,
			type = "activity",
			title = "VIP礼包",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_37",
			is_local_icon = 1,
			gotoUI = {"vip_gift",},
			tag = "hot",
			beginTime = -1,
			endTime = -1,
		},
		[35]=
		{
			id = 35,
			ID = 35,
			noCloseUI = 1,
			order = -27,
			type = "activity",
			title = "万元赛",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_38",
			is_local_icon = 1,
			gotoUI = {"wys_discount",},
			tag = "hot",
			beginTime = -1,
			endTime = -1,
		},
		[36]=
		{
			id = 36,
			ID = 36,
			noCloseUI = 1,
			order = 4,
			type = "activity",
			title = "一元礼包",
			isOnOff = 1,
			showType = "image",
			parmData = "ad_41",
			is_local_icon = 1,
			gotoUI = {"hall_gift_10",},
			tag = "hot",
			beginTime = -1,
			endTime = -1,
		},
		[37]=
		{
			id = 37,
			ID = 37,
			noCloseUI = 1,
			order = -31,
			type = "activity",
			title = "端午礼包",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_40.jpg",
			is_local_icon = 1,
			gotoUI = {"hall_gift_73",},
			tag = "new",
			beginTime = -1,
			endTime = -1,
		},
		[38]=
		{
			id = 38,
			ID = 38,
			noCloseUI = 1,
			order = -30,
			type = "activity",
			title = "端午集粽子",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_42",
			is_local_icon = 0,
			gotoUI = {"act_zongzi",},
			tag = "new",
			beginTime = -1,
			endTime = -1,
		},
		[39]=
		{
			id = 39,
			ID = 39,
			noCloseUI = 1,
			order = 7,
			type = "activity",
			title = "商城特惠",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_618",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop",},
			tag = "hot",
			beginTime = -1,
			endTime = -1,
		},
		[40]=
		{
			id = 40,
			ID = 40,
			noCloseUI = 1,
			order = 1,
			type = "activity",
			title = "新游消消乐",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_998",
			is_local_icon = 1,
			gotoUI = {"game_MiniGame",},
			tag = "hot",
			beginTime = -1,
			endTime = -1,
		},
		[41]=
		{
			id = 41,
			ID = 41,
			noCloseUI = 1,
			order = 0,
			type = "activity",
			title = "父亲节礼包",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_43",
			is_local_icon = 1,
			gotoUI = {"hall_gift",75},
			tag = "normal",
			beginTime = -1,
			endTime = -1,
		},
		[42]=
		{
			id = 42,
			ID = 42,
			noCloseUI = 1,
			order = -1,
			type = "activity",
			title = "一起抽大奖",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_44",
			is_local_icon = 1,
			gotoUI = {"activity_father",},
			tag = "new",
			beginTime = -1,
			endTime = -1,
		},
		[43]=
		{
			id = 43,
			ID = 43,
			noCloseUI = 1,
			order = -2,
			type = "activity",
			title = "宝箱鱼出没",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_bxy",
			is_local_icon = 0,
			tag = "new",
			beginTime = -1,
			endTime = -1,
		},
		[44]=
		{
			id = 44,
			ID = 44,
			noCloseUI = 1,
			order = -50,
			type = "activity",
			title = "月末福利",
			isOnOff = 0,
			showType = "prefab",
			parmData = "activity1",
			is_local_icon = 1,
			tag = "hot",
			beginTime = -1,
			endTime = -1,
		},
		[45]=
		{
			id = 45,
			ID = 45,
			noCloseUI = 1,
			order = 2,
			type = "activity",
			title = "月末礼包",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_47",
			is_local_icon = 1,
			gotoUI = {"hall_gift",101},
			tag = "new",
			beginTime = -1,
			endTime = -1,
		},
		[46]=
		{
			id = 46,
			ID = 46,
			noCloseUI = 1,
			order = 1,
			type = "activity",
			title = "月末狂欢",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_46",
			is_local_icon = 1,
			gotoUI = {"game_FishingHall",},
			tag = "new",
			beginTime = -1,
			endTime = -1,
		},
		[47]=
		{
			id = 47,
			ID = 47,
			noCloseUI = 1,
			order = 6,
			type = "activity",
			title = "关注有礼",
			isOnOff = 1,
			showType = "image",
			parmData = "ad_48",
			is_local_icon = 1,
			gotoUI = {"share_link","{\"type\": 3,\"title\": \"直接【点我】关注官方公众号\",\"description\": \"描述\",\"url\": \"http://cwww.jyhd919.cn/shareHome/index.html\",\"isCircleOfFriends\": \"true\"}"},
			tag = "normal",
			beginTime = -1,
			endTime = -1,
		},
		[48]=
		{
			id = 48,
			ID = 48,
			noCloseUI = 1,
			order = -1,
			type = "activity",
			title = "清凉一夏",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_50",
			is_local_icon = 1,
			gotoUI = {"game_FishingHall",},
			tag = "hot",
			beginTime = -1,
			endTime = 1562601599,
		},
		[49]=
		{
			id = 49,
			ID = 49,
			noCloseUI = 1,
			order = 0,
			type = "activity",
			title = "西瓜礼包",
			isOnOff = 0,
			showType = "image",
			parmData = "ad_51",
			is_local_icon = 1,
			gotoUI = {"hall_gift",102},
			tag = "hot",
			beginTime = -1,
			endTime = 1562601599,
		},
		[50]=
		{
			id = 50,
			ID = 50,
			noCloseUI = 1,
			order = 0,
			type = "activity",
			title = "新人专属",
			isOnOff = 0,
			showType = "prefab",
			parmData = "activity2",
			is_local_icon = 1,
			tag = "hot",
			beginTime = -1,
			endTime = -1,
		},
		[51]=
		{
			id = 51,
			ID = 51,
			noCloseUI = 0,
			order = 1,
			type = "activity",
			title = "全民分享",
			isOnOff = 1,
			showType = "image",
			parmData = "ad_49",
			is_local_icon = 1,
			gotoUI = {"share_activity",},
			tag = "new",
			beginTime = -1,
			endTime = 1564588799,
		},
		[52]=
		{
			id = 52,
			ID = 52,
			noCloseUI = 0,
			order = 2,
			type = "activity",
			title = "全服赚钱",
			isOnOff = 1,
			showType = "image",
			parmData = "ad_52",
			is_local_icon = 1,
			gotoUI = {"money_center",},
			tag = "new",
			beginTime = -1,
			endTime = -1,
		},
		[53]=
		{
			id = 53,
			ID = 53,
			noCloseUI = 1,
			order = 5,
			type = "activity",
			title = "环保家居",
			isOnOff = 1,
			showType = "image",
			parmData = "ad_55",
			is_local_icon = 1,
			gotoUI = {"duihuan_shop","&id=444625",},
			tag = "hot",
			beginTime = -1,
			endTime = -1,
		},
		[54]=
		{
			id = 54,
			ID = 54,
			noCloseUI = 1,
			order = 7,
			type = "activity",
			title = "礼包兑换",
			isOnOff = 1,
			showType = "image",
			parmData = "ad_57",
			is_local_icon = 1,
			gotoUI = {"exchange_gift",},
			tag = "normal",
			beginTime = -1,
			endTime = -1,
		},
		[55]=
		{
			id = 55,
			ID = 55,
			noCloseUI = 1,
			order = 0,
			type = "activity",
			title = "短视频大赛",
			isOnOff = 1,
			showType = "image",
			parmData = "ad_58",
			is_local_icon = 1,
			gotoUI = {"copy_gzh","jyddz02",},
			tag = "new",
			beginTime = -1,
			endTime = -1,
		},
		[56]=
		{
			id = 56,
			ID = 56,
			noCloseUI = 1,
			order = -51,
			type = "activity",
			title = "捕鱼达人榜",
			isOnOff = 1,
			showType = "image",
			parmData = "ad_56",
			is_local_icon = 1,
			gotoUI = {"game_FishingHall",},
			tag = "new",
			beginTime = -1,
			endTime = -1,
		},
	},
}