return {
	hallconfig=
	{
		[1]=
		{
			id = 1,
			bannerID = 1,
			order = 1,
			gotoUI = {"match_hall",},
			srartTime = -1,
			imageName = "hall_banner_1",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[2]=
		{
			id = 2,
			bannerID = 2,
			order = 2,
			gotoUI = {"hall_gzh",},
			srartTime = -1,
			imageName = "hall_banner_9",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[3]=
		{
			id = 3,
			bannerID = 3,
			order = 3,
			gotoUI = {"hall_gzh",},
			srartTime = -1,
			imageName = "hall_banner_9",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[4]=
		{
			id = 4,
			bannerID = 4,
			order = 4,
			gotoUI = {"citymatch_hall",},
			srartTime = -1,
			imageName = "hall_banner_2",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[5]=
		{
			id = 5,
			bannerID = 5,
			order = 5,
			srartTime = -1,
			imageName = "hall_banner_7",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[6]=
		{
			id = 6,
			bannerID = 6,
			order = 6,
			gotoUI = {"free_hall",},
			srartTime = -1,
			imageName = "hall_banner_8",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[7]=
		{
			id = 7,
			bannerID = 7,
			order = 7,
			gotoUI = {"roomcard_hall",},
			srartTime = -1,
			imageName = "hall_banner_3",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[8]=
		{
			id = 8,
			bannerID = 8,
			order = 0,
			gotoUI = {"hall_tgr",},
			srartTime = -1,
			imageName = "hall_banner_11",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[9]=
		{
			id = 9,
			bannerID = 9,
			order = 0,
			gotoUI = {"hall_sd",},
			srartTime = -1,
			imageName = "hall_banner_12",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[10]=
		{
			id = 10,
			bannerID = 10,
			order = -1,
			gotoUI = {"hall_gift_13",},
			srartTime = -1,
			imageName = "hall_banner_14",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[11]=
		{
			id = 11,
			bannerID = 11,
			order = -2,
			gotoUI = {"hall_golden_pig",},
			srartTime = -1,
			imageName = "hall_banner_15",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[12]=
		{
			id = 12,
			bannerID = 12,
			order = 0,
			gotoUI = {"hall_egg",},
			srartTime = -1,
			imageName = "hall_banner_16",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[13]=
		{
			id = 13,
			bannerID = 13,
			order = -3,
			gotoUI = {"hall_gift_21",},
			srartTime = -1,
			imageName = "hall_banner_21",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[14]=
		{
			id = 14,
			bannerID = 14,
			order = -4,
			gotoUI = {"free_hall",},
			srartTime = -1,
			imageName = "hall_banner_18",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[15]=
		{
			id = 15,
			bannerID = 15,
			order = -5,
			gotoUI = {"free_hall",},
			srartTime = -1,
			imageName = "hall_banner_24",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[16]=
		{
			id = 16,
			bannerID = 16,
			order = -6,
			gotoUI = {"hall_gift_28",},
			shop_id = 28,
			srartTime = -1,
			imageName = "hall_banner_22",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[17]=
		{
			id = 17,
			bannerID = 17,
			order = -7,
			gotoUI = {"hall_egg",},
			srartTime = -1,
			imageName = "hall_banner_23",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[18]=
		{
			id = 18,
			bannerID = 18,
			order = -8,
			gotoUI = {"hall_gift_29",},
			shop_id = 29,
			srartTime = -1,
			imageName = "hall_banner_25",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[19]=
		{
			id = 19,
			bannerID = 19,
			order = -9,
			gotoUI = {"hall_egg",},
			srartTime = -1,
			imageName = "hall_banner_26",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[20]=
		{
			id = 20,
			bannerID = 20,
			order = -10,
			gotoUI = {"match_hall","gms",},
			srartTime = -1,
			imageName = "hall_banner_27",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[21]=
		{
			id = 21,
			bannerID = 21,
			order = -10,
			gotoUI = {"match_hall","gms",},
			srartTime = -1,
			imageName = "hall_banner_28",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[22]=
		{
			id = 22,
			bannerID = 22,
			order = -10,
			gotoUI = {"hall_gift_35",},
			shop_id = 35,
			srartTime = -1,
			imageName = "hall_banner_29",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[23]=
		{
			id = 23,
			bannerID = 23,
			order = -11,
			gotoUI = {"hall_egg",},
			srartTime = -1,
			imageName = "hall_banner_26",
			is_local_icon = 0,
			isOnOff = 0,
		},
		[24]=
		{
			id = 24,
			bannerID = 24,
			order = -12,
			srartTime = 1555030800,
			imageName = "hall_banner_30",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[25]=
		{
			id = 25,
			bannerID = 25,
			order = -14,
			gotoUI = {"copy_gzh_sw",},
			srartTime = -1,
			imageName = "hall_banner_46",
			is_local_icon = 1,
			isOnOff = 1,
		},
		[26]=
		{
			id = 26,
			bannerID = 26,
			order = -14,
			gotoUI = {"copy_gzh","JYDDZ01",},
			srartTime = -1,
			imageName = "hall_banner_32",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[27]=
		{
			id = 27,
			bannerID = 27,
			order = -15,
			gotoUI = {"weekly_card",},
			srartTime = -1,
			imageName = "hall_banner_36",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[28]=
		{
			id = 28,
			bannerID = 28,
			order = -15,
			gotoUI = {"hall_egg","mode_cs",},
			srartTime = -1,
			imageName = "hall_banner_37",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[29]=
		{
			id = 29,
			bannerID = 29,
			order = -16,
			gotoUI = {"game_FishingHall","add_glod",},
			srartTime = -1,
			imageName = "hall_banner_34",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[30]=
		{
			id = 30,
			bannerID = 30,
			order = -13,
			gotoUI = {"hall_gift_38",},
			shop_id = 38,
			srartTime = -1,
			imageName = "hall_banner_33",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[31]=
		{
			id = 31,
			bannerID = 31,
			order = -12,
			gotoUI = {"copy_gzh","JYDDZ01",},
			srartTime = -1,
			imageName = "hall_banner_38",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[32]=
		{
			id = 32,
			bannerID = 32,
			order = -17,
			gotoUI = {"vip_gift",},
			srartTime = -1,
			imageName = "hall_banner_40",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[33]=
		{
			id = 33,
			bannerID = 33,
			order = -19,
			gotoUI = {"share_link", "{\"type\": 3,\"title\": \"直接【点我】关注官方公众号\",\"description\": \"描述\",\"url\": \"http://cwww.jyhd919.cn/service/service.html\",\"isCircleOfFriends\": \"true\"}",},
			srartTime = -1,
			imageName = "hall_banner_39",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[34]=
		{
			id = 34,
			bannerID = 34,
			order = -18,
			gotoUI = {"wys_discount",},
			srartTime = 32515960956,
			imageName = "hall_banner_41",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[35]=
		{
			id = 35,
			bannerID = 35,
			order = 0,
			gotoUI = {"share_link", "{\"type\": 3,\"title\": \"【点我】马上领取免费门票继续>>\",\"description\": \"描述\",\"url\": \"http://cwww.jyhd919.cn/kefuWX/index.html\",\"isCircleOfFriends\": \"true\"}",},
			srartTime = -1,
			imageName = "hall_banner_29",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[36]=
		{
			id = 36,
			bannerID = 36,
			order = -20,
			gotoUI = {"hall_gift_10",},
			srartTime = -1,
			imageName = "hall_banner_44.jpg",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[37]=
		{
			id = 37,
			bannerID = 37,
			order = -21,
			gotoUI = {"match_hall","gms",},
			srartTime = -1,
			imageName = "hall_banner_999",
			is_local_icon = 0,
			isOnOff = 0,
		},
		[38]=
		{
			id = 38,
			bannerID = 38,
			order = -23,
			gotoUI = {"act_zongzi",},
			srartTime = 1559610000,
			imageName = "hall_banner_45.jpg",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[39]=
		{
			id = 39,
			bannerID = 39,
			order = -25,
			gotoUI = {"game_MiniGame",},
			srartTime = -1,
			imageName = "hall_banner_998",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[40]=
		{
			id = 40,
			bannerID = 40,
			order = -24,
			gotoUI = {"hall_gift_73",},
			srartTime = -1,
			imageName = "hall_banner_43.jpg",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[41]=
		{
			id = 41,
			bannerID = 41,
			order = -13,
			gotoUI = {"duihuan_shop",},
			srartTime = -1,
			imageName = "hall_banner_618",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[42]=
		{
			id = 42,
			bannerID = 42,
			order = -26,
			gotoUI = {"hall_gift",75},
			srartTime = -1,
			imageName = "hall_banner_47",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[43]=
		{
			id = 43,
			bannerID = 43,
			order = -27,
			gotoUI = {"activity_father",},
			srartTime = -1,
			imageName = "hall_banner_48",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[44]=
		{
			id = 44,
			bannerID = 44,
			order = -28,
			srartTime = -1,
			imageName = "hall_banner_bxy",
			is_local_icon = 0,
			isOnOff = 0,
		},
		[45]=
		{
			id = 45,
			bannerID = 45,
			order = -29,
			gotoUI = {"hall_gift",101},
			srartTime = -1,
			imageName = "hall_banner_51",
			is_local_icon = 1,
			isOnOff = 0,
		},
		[46]=
		{
			id = 46,
			bannerID = 46,
			order = -30,
			gotoUI = {"game_FishingHall",},
			srartTime = -1,
			imageName = "hall_banner_50",
			is_local_icon = 1,
			isOnOff = 1,
		},
		[47]=
		{
			id = 47,
			bannerID = 47,
			order = -31,
			gotoUI = {"share_link","{\"type\": 3,\"title\": \"直接【点我】关注官方公众号\",\"description\": \"描述\",\"url\": \"http://cwww.jyhd919.cn/shareHome/index.html\",\"isCircleOfFriends\": \"true\"}"},
			srartTime = -1,
			imageName = "hall_banner_52",
			is_local_icon = 1,
			isOnOff = 1,
		},
	},
	upconfig=
	{
		[1]=
		{
			id = 1,
			bannerID = 1,
			order = 2,
			gotoUI = "match_hall",
			model = "LoginUp",
			srartTime = -1,
			image = "gy_2",
			isOnOff = 0,
		},
		[2]=
		{
			id = 2,
			bannerID = 2,
			order = 3,
			gotoUI = "citymatch_hall",
			model = "LoginUp",
			srartTime = -1,
			image = "ad_1",
			isOnOff = 0,
		},
		[3]=
		{
			id = 3,
			bannerID = 3,
			order = 4,
			gotoUI = "match_hall",
			model = "LoginUp",
			srartTime = -1,
			image = "gy_3",
			isOnOff = 0,
		},
		[4]=
		{
			id = 4,
			bannerID = 4,
			order = 5,
			gotoUI = "citymatch_hall",
			model = "LoginUp",
			srartTime = -1,
			image = "gy_4",
			isOnOff = 0,
		},
		[5]=
		{
			id = 5,
			bannerID = 5,
			order = 6,
			gotoUI = "free_hall",
			model = "LoginUp",
			srartTime = -1,
			image = "gy_5",
			isOnOff = 0,
		},
		[6]=
		{
			id = 6,
			bannerID = 6,
			order = 1,
			model = "LoginUp",
			srartTime = -1,
			image = "gy_6",
			isOnOff = 0,
		},
		[7]=
		{
			id = 7,
			bannerID = 7,
			order = 0,
			model = "LoginUp",
			srartTime = -1,
			isOnOff = 0,
			ct_id = 21,
		},
		[8]=
		{
			id = 8,
			bannerID = 8,
			order = -1,
			model = "LoginUp",
			srartTime = -1,
			isOnOff = 0,
		},
		[9]=
		{
			id = 9,
			bannerID = 9,
			order = -2,
			gotoUI = "hall_sd",
			model = "LoginUp",
			srartTime = -1,
			isOnOff = 0,
		},
		[10]=
		{
			id = 10,
			bannerID = 10,
			order = -3,
			gotoUI = "hall_gift_13",
			model = "LoginUp",
			srartTime = -1,
			isOnOff = 0,
		},
		[11]=
		{
			id = 11,
			bannerID = 11,
			order = -4,
			gotoUI = "hall_golden_pig",
			model = "LoginUp",
			srartTime = -1,
			isOnOff = 0,
		},
		[12]=
		{
			id = 12,
			bannerID = 12,
			order = -3,
			gotoUI = "bbsc",
			model = "LoginUp",
			srartTime = -1,
			isOnOff = 1,
		},
		[13]=
		{
			id = 13,
			bannerID = 13,
			order = -5,
			gotoUI = "hall_gift_20",
			shop_id = 20,
			model = "LoginUp",
			srartTime = -1,
			isOnOff = 0,
		},
		[14]=
		{
			id = 14,
			bannerID = 14,
			order = -6,
			gotoUI = "hall_gift_21",
			shop_id = 21,
			model = "LoginUp",
			srartTime = -1,
			isOnOff = 0,
		},
		[15]=
		{
			id = 15,
			bannerID = 15,
			order = -7,
			gotoUI = "hall_gift_29",
			shop_id = 29,
			model = "LoginUp",
			srartTime = -1,
			isOnOff = 0,
		},
		[16]=
		{
			id = 16,
			bannerID = 16,
			order = -7,
			gotoUI = "hall_gift_35",
			shop_id = 35,
			model = "LoginUp",
			srartTime = -1,
			isOnOff = 0,
		},
		[17]=
		{
			id = 17,
			bannerID = 17,
			order = -2,
			model = "LoginUp",
			srartTime = -1,
			isOnOff = 1,
		},
		[18]=
		{
			id = 18,
			bannerID = 20,
			order = 0,
			gotoUI = "weekly_card",
			model = "LoginUp",
			srartTime = -1,
			isOnOff = 0,
		},
		[19]=
		{
			id = 19,
			bannerID = 21,
			order = -8,
			gotoUI = "hall_gift_10",
			shop_id = 10,
			model = "LoginUp",
			srartTime = -1,
			isOnOff = 1,
		},
	},
}