return {
	config=
	{
		[1]=
		{
			line = 1,
			act_type = "normal",
			ID = 1,
			title = "不删号内测公告",
			order = 0,
			is_on_off = 1,
			condi_key = "game_activity_show_nor",
			beginTime = -1,
			endTime = -1,
			showType = "notice",
			parmData = "亲爱的玩家朋友们：\n游戏版本升级将于2019年1月16日（周三）上午9点开启第2阶段不删档内测，安卓和IOS版本手机皆可参与游戏，新版本福利high到爆，登录游戏可领。\n内测期间如遇到任务问题或有更好的建议请加客服QQ：4008882620进行反馈。\n\n                                                                    官方运营团队\n                                                                                       2019年1月16日",
			noCloseUI = 0,
		},
		[2]=
		{
			line = 2,
			act_type = "normal",
			ID = 2,
			title = "官方微信群",
			order = 0,
			is_on_off = 0,
			beginTime = -1,
			endTime = -1,
			showType = "notice",
			parmData = "亲爱的玩家朋友们：\n\n游戏官方微信群正式上线啦，请添加客服QQ：4008882620，由客服拉您进群，群里不定时红包雨，还有漂亮的小姐姐小哥哥可以聊天哦，期待您的加入！\n感谢您对本游戏的热爱和支持！\n\n                                                             《鲸鱼家园》运营团队敬上\n                                                                          2018年10月12日",
			noCloseUI = 0,
		},
		[3]=
		{
			line = 3,
			act_type = "normal",
			ID = 3,
			title = "兑奖公告",
			order = 0,
			is_on_off = 1,
			condi_key = "game_activity_show_nor",
			beginTime = -1,
			endTime = -1,
			showType = "notice",
			parmData = "兑换商城温馨提示：\n\n1.福卡是平台回馈给玩家的一种免费获得的累积型兑换券，可以在兑换商城中兑换话费或者实物；福卡可以通过完成牌局任务，参加公益锦标赛赢取，不能通过充值、玩家之间的转让获得；\n\n2.利用BUG等不正当手段获取的福卡，一经查实，福卡将清零及禁止兑换处理；\n\n3.为了更好的向玩家提供服务，兑换商城将会对不同的玩家ID推送不同的礼品内容；\n\n4.为了进行合理的风险控制以及客观情况的要求，兑换存在库存、区域、以及每日兑换频率等限制；\n\n5.根据运营以及供货方的货源情况，我们将不定期上架或者下架礼品内容；\n\n6.官方保留最终解释权。",
			noCloseUI = 0,
		},
		[4]=
		{
			line = 4,
			act_type = "normal",
			ID = 4,
			title = "重要公告",
			order = 0,
			is_on_off = 1,
			condi_key = "game_activity_show_nor",
			beginTime = -1,
			endTime = -1,
			showType = "notice",
			parmData = "重要公告：\n\n本平台倡导绿色休闲游戏，游戏中的鲸币为道具，不具有任何的实际货币价值，只限于玩家在游戏中使用。同时，本平台对玩家的鲸币不提供任何形式的官方回购、直接或间接兑换现金、兑换实物、相互转赠、转让等服务。\n\n在此，本平台明令禁止玩家之间任何形式的鲸币交易，鲸币转让等行为，坚决抵制低俗、不健康或涉及赌博等违法违规行为，以及其他违背游戏公平的作弊行为，一经核实，将被处以禁止登陆游戏、删除游戏数据等处罚。",
			noCloseUI = 0,
		},
		[5]=
		{
			line = 5,
			act_type = "normal",
			ID = 5,
			title = "关注有礼",
			order = 7,
			is_on_off = 1,
			condi_key = "shield_huawei",
			beginTime = -1,
			endTime = -1,
			showType = "image",
			parmData = "ad_48",
			gotoUI = {"share_link","url_gzyl"},
			noCloseUI = 1,
		},
		[6]=
		{
			line = 6,
			act_type = "normal",
			ID = 6,
			title = "礼包兑换",
			order = 9,
			is_on_off = 1,
			condi_key = "game_activity_show_nor",
			beginTime = -1,
			endTime = -1,
			showType = "image",
			parmData = "ad_57",
			gotoUI = {"exchange_gift",},
			noCloseUI = 1,
		},
		[7]=
		{
			line = 7,
			act_type = "normal",
			ID = 7,
			title = "VIP3直通礼包",
			order = -10,
			is_on_off = 1,
			condi_key = "vip2_buygift",
			beginTime = 1585611000,
			endTime = -1,
			showType = "prefab",
			parmData = "sys_vip2_up",
			gotoUI = {"sys_vip2_up","panel"},
			noCloseUI = 1,
			tag = "hot",
		},
		[8]=
		{
			line = 8,
			act_type = "normal",
			ID = 8,
			title = "VIP4直通礼包",
			order = -10,
			is_on_off = 1,
			condi_key = "vip3_show",
			beginTime = 1585611000,
			endTime = -1,
			showType = "prefab",
			parmData = "sys_vip3_guide",
			gotoUI = {"sys_vip3_guide","panel"},
			noCloseUI = 1,
			tag = "hot",
		},
		[9]=
		{
			line = 9,
			act_type = "normal",
			ID = 9,
			title = "16元福卡",
			order = 8,
			is_on_off = 1,
			condi_key = "jyddz_type_plat",
			beginTime = -1,
			endTime = -1,
			showType = "image",
			parmData = "ad_119",
			gotoUI = {"sys_011_CplZh","download"},
			noCloseUI = 1,
			tag = "limit",
		},
		[10]=
		{
			line = 10,
			act_type = "normal",
			ID = 10,
			title = "16元福卡",
			order = 8,
			is_on_off = 1,
			condi_key = "wqp_type_plat",
			beginTime = -1,
			endTime = -1,
			showType = "image",
			parmData = "ad_119",
			gotoUI = {"sys_011_CplZh","download"},
			noCloseUI = 1,
			tag = "limit",
		},
		[11]=
		{
			line = 11,
			act_type = "normal",
			ID = 11,
			title = "超值月卡",
			order = 3,
			is_on_off = 1,
			beginTime = 1589239800,
			endTime = -1,
			showType = "prefab",
			parmData = "sys_011_yueka_new",
			gotoUI = {"sys_011_yueka_new","panel"},
			noCloseUI = 1,
			tag = "hot",
		},
		[12]=
		{
			line = 12,
			act_type = "normal",
			ID = 12,
			title = "全民邀请",
			order = 7,
			is_on_off = 1,
			condi_key = "game_activity_show_nor",
			beginTime = -1,
			endTime = -1,
			showType = "image",
			parmData = "ad_123",
			gotoUI = {"money_center",},
			noCloseUI = 1,
			tag = "new",
		},
		[13]=
		{
			line = 13,
			act_type = "normal",
			ID = 13,
			title = "三元礼包",
			order = 4,
			is_on_off = 1,
			beginTime = -1,
			endTime = -1,
			showType = "prefab",
			parmData = "sys_013_sylb",
			gotoUI = {"sys_013_sylb","panel"},
			noCloseUI = 1,
			tag = "hot",
		},
		[14]=
		{
			line = 14,
			act_type = "normal",
			ID = 14,
			title = "每周领12元",
			order = -10,
			is_on_off = 1,
			condi_key = "vip1_buygift",
			beginTime = -1,
			endTime = -1,
			showType = "prefab",
			parmData = "sys_vip3_up",
			gotoUI = {"sys_vip3_up","panel"},
			noCloseUI = 1,
			tag = "new",
		},
		[15]=
		{
			line = 15,
			act_type = "normal",
			ID = 15,
			title = "VIP1直通礼包",
			order = -10,
			is_on_off = 1,
			condi_key = "actp_buy_gift_bag_10294",
			beginTime = 1592263800,
			endTime = -1,
			showType = "prefab",
			parmData = "sys_016_vip1ztlb",
			gotoUI = {"sys_016_vip1ztlb","panel"},
			noCloseUI = 1,
			tag = "hot",
		},
		[16]=
		{
			line = 16,
			act_type = "normal",
			ID = 16,
			title = "XXXX",
			order = -11,
			is_on_off = 1,
			beginTime = -1,
			endTime = -1,
			showType = "prefab",
			parmData = "sys_018_vip4ffyd",
			gotoUI = {"sys_018_vip4ffyd","panel",},
			noCloseUI = 1,
			tag = "new",
		},
		[17]=
		{
			line = 17,
			act_type = "normal",
			ID = 17,
			title = "兑奖公告",
			order = 0,
			is_on_off = 1,
			condi_key = "game_activity_show_gswzq",
			beginTime = -1,
			endTime = -1,
			showType = "notice",
			parmData = "兑换商城温馨提示：\n\n1.福卡是平台回馈给玩家的一种免费获得的累积型兑换券，可以在兑换商城中兑换话费或者实物；福卡可以通过完成牌局任务，参加公益锦标赛赢取，不能通过充值、玩家之间的转让获得；\n\n2.利用BUG等不正当手段获取的福卡，一经查实，福卡将清零及禁止兑换处理；\n\n3.为了更好的向玩家提供服务，兑换商城将会对不同的玩家ID推送不同的礼品内容；\n\n4.为了进行合理的风险控制以及客观情况的要求，兑换存在库存、区域、以及每日兑换频率等限制；\n\n5.根据运营以及供货方的货源情况，我们将不定期上架或者下架礼品内容；\n\n6.官方保留最终解释权。",
			noCloseUI = 0,
		},
		[18]=
		{
			line = 18,
			act_type = "normal",
			ID = 18,
			title = "重要公告",
			order = 0,
			is_on_off = 1,
			condi_key = "game_activity_show_gswzq",
			beginTime = -1,
			endTime = -1,
			showType = "notice",
			parmData = "重要公告：\n\n本平台倡导绿色休闲游戏，游戏中的鲸币为道具，不具有任何的实际货币价值，只限于玩家在游戏中使用。同时，本平台对玩家的鲸币不提供任何形式的官方回购、直接或间接兑换现金、兑换实物、相互转赠、转让等服务。\n\n在此，本平台明令禁止玩家之间任何形式的鲸币交易，鲸币转让等行为，坚决抵制低俗、不健康或涉及赌博等违法违规行为，以及其他违背游戏公平的作弊行为，一经核实，将被处以禁止登陆游戏、删除游戏数据等处罚。",
			noCloseUI = 0,
		},
		[19]=
		{
			line = 19,
			act_type = "weekly",
			ID = 19,
			title = "比赛预约",
			order = 1,
			is_on_off = 0,
			condi_key = "game_activity_show_nor",
			beginTime = 1611617400,
			endTime = 1612011599,
			showType = "prefab",
			parmData = "act_044_bsyy",
			gotoUI = {"act_044_bsyy","panel"},
			noCloseUI = 1,
		},
		[20]=
		{
			line = 20,
			act_type = "weekly",
			ID = 20,
			title = "阳光换好礼",
			order = 2,
			is_on_off = 0,
			beginTime = 1611617400,
			endTime = 1612195199,
			showType = "prefab",
			parmData = "act_ty_exchange",
			gotoUI = {"act_ty_exchange","exchange_yghhl","panel"},
			noCloseUI = 1,
		},
		[21]=
		{
			line = 21,
			act_type = "weekly",
			ID = 21,
			title = "消消乐榜单",
			order = 3,
			is_on_off = 0,
			beginTime = 1611617400,
			endTime = 1612195199,
			showType = "prefab",
			parmData = "act_ty_rank",
			gotoUI = {"act_ty_rank","rank_xxlbd","panel"},
			noCloseUI = 1,
		},
		[22]=
		{
			line = 22,
			act_type = "weekly",
			ID = 22,
			title = "好友召回",
			order = 4,
			is_on_off = 0,
			beginTime = 1611617400,
			endTime = 1612195199,
			showType = "prefab",
			parmData = "act_005_ymfl_hyzh",
			gotoUI = {"act_005_ymfl_hyzh","panel"},
			noCloseUI = 1,
		},
		[23]=
		{
			line = 23,
			act_type = "normal",
			ID = 23,
			title = "新鱼上线",
			order = -12,
			is_on_off = 0,
			condi_key = "game_activity_show_nor",
			beginTime = 1611617400,
			endTime = 1612195199,
			showType = "image",
			parmData = "ad_148",
			gotoUI = {"game_FishingHall",},
			noCloseUI = 1,
		},
		[24]=
		{
			line = 24,
			act_type = "weekly",
			ID = 24,
			title = "五福送豪礼",
			order = 1,
			is_on_off = 0,
			beginTime = 1612222200,
			endTime = 1612799999,
			showType = "prefab",
			parmData = "act_047_wfshl",
			gotoUI = {"act_047_wfshl","panel"},
			noCloseUI = 1,
		},
		[25]=
		{
			line = 25,
			act_type = "weekly",
			ID = 25,
			title = "福气达人",
			order = 2,
			is_on_off = 0,
			beginTime = 1612222200,
			endTime = 1612799999,
			showType = "prefab",
			parmData = "act_ty_rank",
			gotoUI = {"act_ty_rank","rank_fqdr","panel"},
			noCloseUI = 1,
		},
		[26]=
		{
			line = 26,
			act_type = "weekly",
			ID = 26,
			title = "新年红包",
			order = 3,
			is_on_off = 0,
			beginTime = 1612222200,
			endTime = 1612799999,
			showType = "prefab",
			parmData = "act_ty_task",
			gotoUI = {"act_ty_task","cjs_049_xnhb","panel"},
			noCloseUI = 1,
		},
		[27]=
		{
			line = 27,
			act_type = "weekly",
			ID = 27,
			title = "新年好礼",
			order = 1,
			is_on_off = 0,
			beginTime = 1612827000,
			endTime = 1613404799,
			showType = "prefab",
			parmData = "act_ty_exchange",
			gotoUI = {"act_ty_exchange","exchange_xnhl","panel"},
			noCloseUI = 1,
		},
		[28]=
		{
			line = 28,
			act_type = "weekly",
			ID = 28,
			title = "新年福袋",
			order = 2,
			is_on_off = 0,
			beginTime = 1612827000,
			endTime = 1613404799,
			showType = "prefab",
			parmData = "act_044_xnfd",
			gotoUI = {"act_044_xnfd","panel"},
			noCloseUI = 1,
		},
		[29]=
		{
			line = 29,
			act_type = "weekly",
			ID = 29,
			title = "压岁钱榜单",
			order = 3,
			is_on_off = 0,
			beginTime = 1612827000,
			endTime = 1613404799,
			showType = "prefab",
			parmData = "act_ty_rank",
			gotoUI = {"act_ty_rank","rank_ysqbd","panel"},
			noCloseUI = 1,
		},
		[30]=
		{
			line = 30,
			act_type = "weekly",
			ID = 30,
			title = "21:30拆福卡",
			order = 4,
			is_on_off = 0,
			beginTime = 1612827000,
			endTime = 1613404799,
			showType = "image",
			parmData = "ad_149",
			gotoUI = {"act_015_yybjsj","panel"},
			noCloseUI = 1,
		},
		[31]=
		{
			line = 31,
			act_type = "weekly",
			ID = 31,
			title = "财神送礼",
			order = 1,
			is_on_off = 0,
			beginTime = 1613431800,
			endTime = 1614009599,
			showType = "prefab",
			parmData = "act_ycs_cssl",
			gotoUI = {"act_ycs_cssl","panel"},
			noCloseUI = 1,
		},
		[32]=
		{
			line = 32,
			act_type = "weekly",
			ID = 32,
			title = "元宝兑换",
			order = 2,
			is_on_off = 0,
			beginTime = 1613431800,
			endTime = 1614009599,
			showType = "prefab",
			parmData = "act_ty_exchange",
			gotoUI = {"act_ty_exchange","exchange_ybdh","panel"},
			noCloseUI = 1,
		},
		[33]=
		{
			line = 33,
			act_type = "weekly",
			ID = 33,
			title = "财气榜单",
			order = 3,
			is_on_off = 0,
			beginTime = 1613431800,
			endTime = 1614009599,
			showType = "prefab",
			parmData = "act_ty_rank",
			gotoUI = {"act_ty_rank","rank_cqbd","panel"},
			noCloseUI = 1,
		},
		[34]=
		{
			line = 34,
			act_type = "weekly",
			ID = 34,
			title = "新游豪礼",
			order = 4,
			is_on_off = 0,
			condi_key = "actp_own_task_21524",
			beginTime = 1613431800,
			endTime = 1614009599,
			showType = "prefab",
			parmData = "act_049_xyhl",
			gotoUI = {"act_049_xyhl","panel"},
			noCloseUI = 1,
		},
		[35]=
		{
			line = 35,
			act_type = "weekly",
			ID = 35,
			title = "比赛预约",
			order = 1,
			is_on_off = 0,
			beginTime = 1614036600,
			endTime = 1614430799,
			showType = "prefab",
			parmData = "act_ty_bsyy",
			gotoUI = {"act_ty_bsyy","panel"},
			noCloseUI = 1,
		},
		[36]=
		{
			line = 36,
			act_type = "weekly",
			ID = 36,
			title = "元宵宝箱",
			order = 3,
			is_on_off = 0,
			beginTime = 1614036600,
			endTime = 1614614399,
			showType = "prefab",
			parmData = "act_050_yxbx",
			gotoUI = {"act_050_yxbx","panel"},
			noCloseUI = 1,
		},
		[37]=
		{
			line = 37,
			act_type = "weekly",
			ID = 37,
			title = "元宵图鉴",
			order = 4,
			is_on_off = 0,
			beginTime = 1614036600,
			endTime = 1614614399,
			showType = "prefab",
			parmData = "act_050_yxtj",
			gotoUI = {"act_050_yxtj","panel"},
			noCloseUI = 1,
		},
		[38]=
		{
			line = 38,
			act_type = "weekly",
			ID = 38,
			title = "积分达人",
			order = 5,
			is_on_off = 0,
			beginTime = 1614036600,
			endTime = 1614614399,
			showType = "prefab",
			parmData = "act_ty_rank",
			gotoUI = {"act_ty_rank","rank_nyx_jfdr","panel"},
			noCloseUI = 1,
		},
		[39]=
		{
			line = 39,
			act_type = "weekly",
			ID = 39,
			title = "好友召回",
			order = 6,
			is_on_off = 0,
			beginTime = 1614036600,
			endTime = 1614614399,
			showType = "prefab",
			parmData = "act_005_ymfl_hyzh",
			gotoUI = {"act_005_ymfl_hyzh","panel"},
			noCloseUI = 1,
		},
		[40]=
		{
			line = 40,
			act_type = "weekly",
			ID = 40,
			title = "有奖问答",
			order = 2,
			is_on_off = 0,
			beginTime = 1614036600,
			endTime = 1614614399,
			showType = "prefab",
			parmData = "act_ty_prize_quiz",
			gotoUI = {"act_ty_prize_quiz","panel"},
			noCloseUI = 1,
		},
		[41]=
		{
			line = 41,
			act_type = "weekly",
			ID = 41,
			title = "祈福好礼",
			order = 1,
			is_on_off = 0,
			beginTime = 1615246200,
			endTime = 1615823999,
			showType = "prefab",
			parmData = "act_052_qfhl",
			gotoUI = {"act_052_qfhl","panel"},
			noCloseUI = 1,
		},
		[42]=
		{
			line = 42,
			act_type = "weekly",
			ID = 42,
			title = "龙腾福利",
			order = 2,
			is_on_off = 0,
			beginTime = 1615246200,
			endTime = 1615823999,
			showType = "prefab",
			parmData = "act_ty_task",
			gotoUI = {"act_ty_task","ltqf_052_ltfl","panel"},
			noCloseUI = 1,
		},
		[43]=
		{
			line = 43,
			act_type = "weekly",
			ID = 43,
			title = "福气达人",
			order = 3,
			is_on_off = 0,
			beginTime = 1615246200,
			endTime = 1615823999,
			showType = "prefab",
			parmData = "act_ty_rank",
			gotoUI = {"act_ty_rank","rank_ltqf_fqdr","panel"},
			noCloseUI = 1,
		},
		[44]=
		{
			line = 44,
			act_type = "weekly",
			ID = 44,
			title = "桃花送礼",
			order = 1,
			is_on_off = 0,
			beginTime = 1615851000,
			endTime = 1616428799,
			showType = "prefab",
			parmData = "act_ty_exchange",
			gotoUI = {"act_ty_exchange","exchange_thsl","panel"},
			noCloseUI = 1,
		},
		[45]=
		{
			line = 45,
			act_type = "weekly",
			ID = 45,
			title = "积分排行榜",
			order = 2,
			is_on_off = 0,
			beginTime = 1615851000,
			endTime = 1616428799,
			showType = "prefab",
			parmData = "act_ty_rank",
			gotoUI = {"act_ty_rank","rank_chdd_jfphb","panel"},
			noCloseUI = 1,
		},
		[46]=
		{
			line = 46,
			act_type = "weekly",
			ID = 46,
			title = "新春福利",
			order = 3,
			is_on_off = 0,
			beginTime = 1615851000,
			endTime = 1616428799,
			showType = "prefab",
			parmData = "act_ty_task",
			gotoUI = {"act_ty_task","chdd_053_xcfl","panel"},
			noCloseUI = 1,
		},
		[47]=
		{
			line = 47,
			act_type = "weekly",
			ID = 47,
			title = "比赛预约",
			order = 1,
			is_on_off = 0,
			beginTime = 1616455800,
			endTime = 1617033599,
			showType = "prefab",
			parmData = "act_ty_bsyy",
			gotoUI = {"act_ty_bsyy","panel"},
			noCloseUI = 1,
		},
		[48]=
		{
			line = 48,
			act_type = "weekly",
			ID = 48,
			title = "游戏达人",
			order = 2,
			is_on_off = 0,
			beginTime = 1616455800,
			endTime = 1617033599,
			showType = "prefab",
			parmData = "act_ty_rank",
			gotoUI = {"act_ty_rank","rank_hljnh_yxdr","panel"},
			noCloseUI = 1,
		},
		[49]=
		{
			line = 49,
			act_type = "weekly",
			ID = 49,
			title = "捕鱼能手",
			order = 3,
			is_on_off = 0,
			beginTime = 1616455800,
			endTime = 1617033599,
			showType = "prefab",
			parmData = "act_053_byns",
			gotoUI = {"act_053_byns","panel"},
			noCloseUI = 1,
		},
		[50]=
		{
			line = 50,
			act_type = "weekly",
			ID = 50,
			title = "消除能手",
			order = 4,
			is_on_off = 0,
			beginTime = 1616455800,
			endTime = 1617033599,
			showType = "prefab",
			parmData = "act_053_xcns",
			gotoUI = {"act_053_xcns","panel"},
			noCloseUI = 1,
		},
		[51]=
		{
			line = 51,
			act_type = "weekly",
			ID = 51,
			title = "祭祖祈福",
			order = 1,
			is_on_off = 1,
			beginTime = 1617060600,
			endTime = 1617638399,
			showType = "prefab",
			parmData = "act_054_jzqf",
			gotoUI = {"act_054_jzqf","panel"},
			noCloseUI = 1,
		},
		[52]=
		{
			line = 52,
			act_type = "weekly",
			ID = 52,
			title = "好礼兑换",
			order = 2,
			is_on_off = 1,
			beginTime = 1617060600,
			endTime = 1617638399,
			showType = "prefab",
			parmData = "act_ty_exchange",
			gotoUI = {"act_ty_exchange","exchange_qmjz_hldh","panel"},
			noCloseUI = 1,
		},
		[53]=
		{
			line = 53,
			act_type = "weekly",
			ID = 53,
			title = "积分榜单",
			order = 3,
			is_on_off = 1,
			beginTime = 1617060600,
			endTime = 1617638399,
			showType = "prefab",
			parmData = "act_ty_rank",
			gotoUI = {"act_ty_rank","rank_qmjz_jfbd","panel"},
			noCloseUI = 1,
		},
		[54]=
		{
			line = 54,
			act_type = "normal",
			ID = 54,
			title = "系统升级奖励",
			order = -11,
			is_on_off = 1,
			beginTime = -1,
			endTime = 1617638399,
			showType = "prefab",
			parmData = "act_sjjl",
			gotoUI = {"act_sjjl","panel",},
			noCloseUI = 1,
			tag = "new",
		},
	},
}