return {
	config=
	{
		[1]=
		{
			line = 1,
			act_type = "normal",
			ID = 1,
			title = "重要公告",
			order = 5,
			is_on_off = 1,
			beginTime = -1,
			endTime = -1,
			showType = "notice",
			parmData = "重要公告：\n\n本平台倡导绿色休闲游戏，游戏中的金币为道具，不具有任何的实际货币价值，只限于玩家在游戏中使用。同时，本平台对玩家的金币不提供任何形式的官方回购、直接或间接兑换现金、兑换实物、相互转赠、转让等服务。\n\n在此，本平台明令禁止玩家之间任何形式的金币交易，金币转让等行为，坚决抵制低俗、不健康或涉及赌博等违法违规行为，以及其他违背游戏公平的作弊行为，一经核实，将被处以禁止登陆游戏、删除游戏数据等处罚。",
			noCloseUI = 0,
			tag = "normal",
		},
		[2]=
		{
			line = 2,
			act_type = "normal",
			ID = 2,
			title = "三元礼包",
			order = 3,
			is_on_off = 1,
			condi_key = "yylb",
			beginTime = -1,
			endTime = -1,
			showType = "image",
			parmData = "3ylb_dk_bg",
			gotoUI = {"hall_gift",10},
			noCloseUI = 1,
			tag = "hot",
		},
		[3]=
		{
			line = 3,
			act_type = "normal",
			ID = 3,
			title = "礼包兑换",
			order = 9,
			is_on_off = 1,
			condi_key = "lbdh",
			beginTime = -1,
			endTime = -1,
			showType = "image",
			parmData = "lbdh_dk_bg",
			gotoUI = {"exchange_gift",},
			noCloseUI = 1,
			tag = "normal",
		},
		[4]=
		{
			line = 4,
			act_type = "normal",
			ID = 4,
			title = "vip2直通礼包",
			order = -10,
			is_on_off = 1,
			condi_key = "vip1_buygift",
			beginTime = 1585611000,
			endTime = -1,
			showType = "prefab",
			parmData = "act_023_vip2ztlb",
			gotoUI = {"act_023_vip2ztlb","panel"},
			noCloseUI = 1,
			tag = "hot",
		},
		[5]=
		{
			line = 5,
			act_type = "normal",
			ID = 5,
			title = "vip3直通礼包",
			order = -10,
			is_on_off = 1,
			condi_key = "vip2_buygift",
			beginTime = 1585611000,
			endTime = -1,
			showType = "prefab",
			parmData = "act_023_vip3ztlb",
			gotoUI = {"act_023_vip3ztlb","panel"},
			noCloseUI = 1,
			tag = "hot",
		},
		[6]=
		{
			line = 6,
			act_type = "normal",
			ID = 6,
			title = "vip4直通礼包",
			order = -10,
			is_on_off = 1,
			condi_key = "vip3_buygift",
			beginTime = 1585611000,
			endTime = -1,
			showType = "prefab",
			parmData = "act_023_vip4ztlb",
			gotoUI = {"act_023_vip4ztlb","panel"},
			noCloseUI = 1,
			tag = "hot",
		},
		[7]=
		{
			line = 7,
			act_type = "normal",
			ID = 7,
			title = "超值月卡",
			order = -9,
			is_on_off = 1,
			beginTime = 1589239800,
			endTime = -1,
			showType = "prefab",
			parmData = "sys_011_yueka_new",
			gotoUI = {"sys_011_yueka_new","panel1"},
			noCloseUI = 1,
			tag = "hot",
		},
		[8]=
		{
			line = 8,
			act_type = "normal",
			ID = 8,
			title = "vip1直通礼包",
			order = -10,
			is_on_off = 1,
			condi_key = "vip0_buygift",
			beginTime = 1585611000,
			endTime = -1,
			showType = "prefab",
			parmData = "act_033_vip1ztlb",
			gotoUI = {"act_033_vip1ztlb","panel"},
			noCloseUI = 1,
			tag = "hot",
		},
		[9]=
		{
			line = 9,
			act_type = "normal",
			ID = 9,
			title = "周卡",
			order = -8,
			is_on_off = 1,
			condi_key = "cpl_cjj",
			beginTime = -1,
			endTime = -1,
			showType = "prefab",
			parmData = "sys_act_czzk",
			gotoUI = {"sys_act_czzk","panel"},
			noCloseUI = 1,
			tag = "hot",
		},
		[10]=
		{
			line = 10,
			act_type = "normal",
			ID = 28,
			title = "系统升级奖励",
			order = -20,
			is_on_off = 1,
			beginTime = 1614643200,
			endTime = -1,
			showType = "prefab",
			parmData = "act_sjjl",
			gotoUI = {"act_sjjl","panel"},
			noCloseUI = 1,
			tag = "new",
		},
		[11]=
		{
			line = 11,
			act_type = "weekly",
			ID = 29,
			title = "好礼兑换",
			order = 1,
			is_on_off = 1,
			beginTime = 1629761400,
			endTime = 1630339199,
			showType = "prefab",
			parmData = "act_ty_exchange",
			gotoUI = {"act_ty_exchange","exchange_khqd_hldh_02","panel"},
			noCloseUI = 1,
		},
		[12]=
		{
			line = 12,
			act_type = "weekly",
			ID = 30,
			title = "庆典榜单",
			order = 3,
			is_on_off = 1,
			beginTime = 1629761400,
			endTime = 1630339199,
			showType = "prefab",
			parmData = "act_ty_rank",
			gotoUI = {"act_ty_rank","rank_etjkl_jfphb","panel"},
			noCloseUI = 1,
		},
		[13]=
		{
			line = 13,
			act_type = "weekly",
			ID = 31,
			title = "节日礼包",
			order = 2,
			is_on_off = 0,
			beginTime = 1625527800,
			endTime = 1626105599,
			showType = "prefab",
			parmData = "act_058_jrlb",
			gotoUI = {"act_058_jrlb","panel"},
			noCloseUI = 1,
		},
		[14]=
		{
			line = 14,
			act_type = "weekly",
			ID = 32,
			title = "游戏达人",
			order = 1,
			is_on_off = 0,
			beginTime = 1629156600,
			endTime = 1629734399,
			showType = "prefab",
			parmData = "act_ty_rank",
			gotoUI = {"act_ty_rank","rank_hljnh_yxdr_03","panel"},
			noCloseUI = 1,
		},
		[15]=
		{
			line = 15,
			act_type = "weekly",
			ID = 33,
			title = "捕鱼能手",
			order = 2,
			is_on_off = 0,
			beginTime = 1629156600,
			endTime = 1629734399,
			showType = "prefab",
			parmData = "act_053_byns",
			gotoUI = {"act_053_byns","panel"},
			noCloseUI = 1,
		},
		[16]=
		{
			line = 16,
			act_type = "weekly",
			ID = 34,
			title = "消除能手",
			order = 3,
			is_on_off = 1,
			beginTime = 1629156600,
			endTime = 1629734399,
			showType = "prefab",
			parmData = "act_053_xcns",
			gotoUI = {"act_053_xcns","panel"},
			noCloseUI = 1,
		},
		[17]=
		{
			line = 17,
			act_type = "weekly",
			ID = 35,
			title = "连购返利",
			order = 2,
			is_on_off = 1,
			condi_key = "actp_own_task_p_continuity_shop_v4up",
			beginTime = 1629761400,
			endTime = 1630339199,
			showType = "prefab",
			parmData = "act_ty_task",
			gotoUI = {"act_ty_task","khqd_054_lgfl_v4","panel"},
			noCloseUI = 1,
		},
		[18]=
		{
			line = 18,
			act_type = "weekly",
			ID = 36,
			title = "连购返利",
			order = 2,
			is_on_off = 1,
			condi_key = "actp_own_task_p_continuity_shop_nor",
			beginTime = 1629761400,
			endTime = 1630339199,
			showType = "prefab",
			parmData = "act_ty_task",
			gotoUI = {"act_ty_task","khqd_054_lgfl_nor","panel"},
			noCloseUI = 1,
		},
		[19]=
		{
			line = 19,
			act_type = "weekly",
			ID = 37,
			title = "疯狂抽大奖",
			order = 1,
			is_on_off = 0,
			beginTime = 1626737400,
			endTime = 1627315199,
			showType = "prefab",
			parmData = "act_062_fkcdj",
			gotoUI = {"act_062_fkcdj","panel"},
			noCloseUI = 1,
		},
		[20]=
		{
			line = 20,
			act_type = "weekly",
			ID = 38,
			title = "新游福利",
			order = 1,
			is_on_off = 0,
			beginTime = 1627342200,
			endTime = 1627919999,
			showType = "prefab",
			parmData = "act_ty_yxhd",
			gotoUI = {"act_ty_yxhd","panel"},
			noCloseUI = 1,
		},
		[21]=
		{
			line = 21,
			act_type = "weekly",
			ID = 39,
			title = "丰收礼包",
			order = 2,
			is_on_off = 0,
			beginTime = 1627947000,
			endTime = 1628524799,
			showType = "prefab",
			parmData = "act_059_dwjj_jrlb",
			gotoUI = {"act_059_dwjj_jrlb","panel"},
			noCloseUI = 1,
		},
	},
}